// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt40b5rfFni45Uu9HoKBi4GO2VMTSnMs4',
    appId: '1:444604650284:web:e06bd9e009aed41f849289',
    messagingSenderId: '444604650284',
    projectId: 'easyshopping-d73a6',
    authDomain: 'easyshopping-d73a6.firebaseapp.com',
    storageBucket: 'easyshopping-d73a6.firebasestorage.app',
    measurementId: 'G-K68TMR5BHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGpIY_rDtchHzxy_ipPv-Kd4BdOn4mk_M',
    appId: '1:444604650284:android:00bf2b7c30236bef849289',
    messagingSenderId: '444604650284',
    projectId: 'easyshopping-d73a6',
    storageBucket: 'easyshopping-d73a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefphH8RtvLTtVdMhzanVRoXBBWhBlsr8',
    appId: '1:444604650284:ios:58ac51b3c9a2bbe1849289',
    messagingSenderId: '444604650284',
    projectId: 'easyshopping-d73a6',
    storageBucket: 'easyshopping-d73a6.firebasestorage.app',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefphH8RtvLTtVdMhzanVRoXBBWhBlsr8',
    appId: '1:444604650284:ios:58ac51b3c9a2bbe1849289',
    messagingSenderId: '444604650284',
    projectId: 'easyshopping-d73a6',
    storageBucket: 'easyshopping-d73a6.firebasestorage.app',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt40b5rfFni45Uu9HoKBi4GO2VMTSnMs4',
    appId: '1:444604650284:web:50ade0514f0dd8e1849289',
    messagingSenderId: '444604650284',
    projectId: 'easyshopping-d73a6',
    authDomain: 'easyshopping-d73a6.firebaseapp.com',
    storageBucket: 'easyshopping-d73a6.firebasestorage.app',
    measurementId: 'G-8V5G2ERPRN',
  );
}
